name: Preflight

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

# Ensures that we cancel running jobs for the same PR / same workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run preflight script
        run: ./scripts/preflight.sh
